language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

script:
  - echo $THING
  - ./gradlew build
  - cat /home/travis/build/newfivefour/TravisCITest/app/build/outputs/lint-results-debug.xml
  - >
    curl
    -F "status=2"
    -F "notify=1"
    -F "notes=Some new features and fixed bugs."
    -F "notes_type=0"
    -F "ipa=@app/build/outputs/apk/app-debug.apk"
    -H "X-HockeyAppToken: $HOCKEYAPP_TOKEN"
    https://rink.hockeyapp.net/api/2/apps/upload
